### ISSUE TITLE
Raw fastq files for comparison

### ISSUE THREAD

**Issue by dbolotin** [Mangul-Lab-USC/imrep-figures#1]
Hi,

Congratulations on your publication in Nature Communications!

We want to reproduce part of your results, to check whether the difference in software performance is due to the quality filtering built into MiXCR (which can be turned off by `-ObadQualityThreshold=0` on the `assemble` step).

Can you point us at the raw data used for the comparison?

All the best,
Dmitry.

**Comment by JRotman** [comment]
Hi Dmitry,

Thank you! 

I apologize for the delay in our response. Unfortunately, we no longer have the raw fastq files downloaded. However, all of our data sources are highlighted in the data availability section of the publication, which I am copying here:

All RNA-Seq data discussed in this paper is available as part of the Genotype-Tissue Expression (GTEx) Project under the phs000424.v8.p2 accession number in the database of Genotypes and Phenotypes (dbGaP). The targeted BCR-Seq assemblies used for validation of the ImReP method are available at the adaptive biosystems webpage (https://clients.adaptivebiotech.com/pub/lombardo-2017-bloodadvances). RNA-Seq samples used for validation of ImReP are available under the SRP099346 accession number in the Sequence Read Archive. Raw sequence reads of targeted BCR-Seq data are available under the EGAN00001419382 accession number in the European Genome-Phenome Archive.

Further, if you are interested in rerunning the comparison using the GTEx data (phs000424.v8.p2) please reference [Supplementary_Data_4.csv](https://github.com/Mangul-Lab-USC/ImReP_publication/blob/master/supplementary/Supplementary_Data_4.csv) where all of the SRA accessions for the samples are listed.
